### ISSUE TITLE
【休暇申請画面】申請済みの休暇が画面に表示されている

### ISSUE THREAD

**Issue by alish22334** [alice0de0sho/attendance#1]
# バグ内容
申請済みの休暇がデータテーブルに表示される

# 実行環境
Windows10 GoogleChrome

# 再現手順
1.【勤怠状況画面】で「全休」、「午前休」、「午後休」の情報を登録する
2.【休暇申請画面】でチェックを付けて申請ボタンを押下し、休暇情報を申請する
3.再度、上記「1.」を行う
4.【休暇申請画面】に遷移すると上記「2.」で申請した休暇情報がデータテーブルに表示されている

# 想定
未申請の休暇のみ【休暇申請画面】のデータテーブルに表示される

**Comment by alice0de0sho** [comment]
対応完了

**Comment by alish22334** [comment]
対応完了
